server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgrestest
    password: test@1990
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      validation-timeout: 1000
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true  # Pretty prints SQL queries
        use_sql_comments: false

#logging:
#  level:
#    root: INFO
   # com.external.demo: INFO
 #   org.springframework.jdbc.core: DEBUG  # Logs SQL execution details
 #   org.hibernate.SQL: DEBUG  # Logs Hibernate-generated SQL queries
 #   org.hibernate.type.descriptor.sql: TRACE  # Logs SQL parameters

app:
  name: "Externalized Config - Dev test"
  version: "1.0-DEV abc"

config:
  external:
    path: "E:/config_external/"  
    file: "my-custom-config"
