spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/prod_db
    username: prod_user
    password: prod_pass
  profiles:
    active: prod
message: "This is the Production Environment"
