spring:
  application:
    name: spring_user_client

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  profiles:
 #   active: dev  # ✅ Set active profile

sonar:
  host: http://localhost:9000  # ✅ SonarQube URL
  login: admin
  password: admin
  projectKey: spring_user_client
  projectName: Spring User Client
